### ISSUE TITLE
Support Node v20

### ISSUE THREAD

**Issue by jplandry908** [charoitel/lambda-layer-canvas-nodejs#24]
First off, thank you for your hard work on this. Do you have any plans to support the new Node v20 runtime?

**Comment by charoitel** [comment]
@jplandry908, currently is still under planning, may include node 20 support when the next release of node-canvas is available, thanks

**Comment by swipht1991** [comment]
Thank you for providing this. Is node 20 support still a part of the plan for a future release?

**Comment by charoitel** [comment]
@swipht1991, yes and actually Node 20 should be supported. For reference, according to https://github.com/Automattic/node-canvas/issues/2232, Node 16 may be dropped in node-canvas 3.0.0.

These days I am wondering, in case the new release of node-canvas still not available in upcoming few months, may be I would release a maintenance release which would try to include support for Node 20 first.

Please feel free to let me know if there is any concern, or if there is anything would like to include or discuss. Thanks~

**Comment by swipht1991** [comment]
@charoitel That sounds great, thank you for the detailed update. I hadn't realized node-canvas wasn't providing node 20 support until 3.0.0. Since node 18 still has support I don't think there is a huge urgency to get node 20 supported, but a maintenance release of node-canvas to ensure that is available would be appreciated. It's good to know it's still on the plan and will be made available when node-canvas 3.0.0 is out.

Thanks again for providing this.

**Comment by deathemperor** [comment]
just wanna chime in that node-canvas support node 20 in its latest release https://github.com/Automattic/node-canvas/releases/tag/v2.11.2

**Comment by splunkettCB** [comment]
@charoitel since the above node-canvas release supports node20 would it be possible to have a new version of lambda layer  built to support 20?

**Comment by sepiaflux** [comment]
Hi, is there any progress on this?:)

**Comment by charoitel** [comment]
Thanks everyone for your patience, my apologies to keep you waiting that long, the new release that supports node20 has just released on [GitHub](https://github.com/charoitel/lambda-layer-canvas-nodejs/releases/tag/2.11.4) and [Serverless Application Repository](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:990551184979:applications~lambda-layer-canvas-nodejs). However, in order to make the size as minimal as possible, the release has been separated into small packages by node version: 16, 18 and 20.

In addition, during the testing, it is found that the data URI being generated could be different under node20, you may refer to the fix in the konva test script. Besides node20 support, fabric v6 is also now supported.

Do you think that may be good to separate the layer packages not just by node version but also by dependency like canvas-node20 and canvas-fabric-node20? Please feel free to suggest and leave your comments. Thank you.
